### PR TITLE
Tas 11/ Add command alias

### LINKED ISSUE #11: Add subcommands alias
Ex:

`compute-env` -> `ce`
`credentials` -> `creds`
`pipelines` -> `pipes`

### PR DESCRIPTION
**Pull request by grananda**

### CODE REVIEW

**Review by jordeu — CHANGES_REQUESTED** [review]
Update to the latest picocli 4.6.2. This was on hold because previous picocli version the autocomplete was not working properly with command alias, check that with the new version it is working.

**Comment by grananda** [comment]
Autocomplete ok

image

**Comment by jordeu** [comment]
No autocomplete it is not working for alias subcommands. You need to upgrade picocli
Screenshot from 2021-11-30 08-48-45
.

**Comment by jordeu** [comment]
Oops, picocli v4.6.2 is not fixing this as expected. I'm going to convert this into a draft and remove the issue from current milestone.

**Comment by jordeu** [comment]
I'm going to close this PR. We can reopen it when picocli solves this problem.

**Pull request closed without merging**
