### PR TITLE
AWS CodeCommit credentials support

### LINKED ISSUE #387: Add support for AWS CodeCommit credentials
Add support for CodeCommit credentials provider through the CLI to be able to create/delete/update:
```bash
tw credentials add codecommit
```
```bash
tw credentials update codecommit
```

With the following options, ideally:
```console
Options:
* -n, --name=<name>                       Credentials name.
  -w, --workspace=<workspace>             Workspace numeric identifier (TOWER_WORKSPACE_ID as default) or workspace reference as OrganizationName/WorkspaceName
      --overwrite                         Overwrite the credentials if it already exists.
  -a, --access-key=<accessKey>            The AWS access key of IAM account to access target repository.
  -s, --secret-key=<secretKey>
  -u, --repository-url=<repositoryBaseURL>
  ```

### PR DESCRIPTION
**Pull request by JaimeSeqLabs**
## Description

Closes #387 

Adds support for creating/updating/deleting AWS CodeCommit credentials.

## Guidelines for testing

Create new CodeCommit credentials:
```
$> ./tw credentials add codecommit -n CCTest --access-key=<access_key> --secret-key=<secret_key> --base-url=https://git-codecommit.eu-west-1.amazonaws.com

  New CODECOMMIT credentials 'CCTest (3dm8ipcP5manEAxMjAMAip)' added at user workspace
```

Update CodeCommit credentials:
```
$> ./tw credentials update codecommit -n CCTest --access-key=<new_access_key> --secret-key=<secret_key>

  CODECOMMIT credentials 'CCTest' updated at user workspace
```

Delete CodeCommit credentials:
```
$> ./tw credentials delete -n CCTest

  Credentials '3dm8ipcP5manEAxMjAMAip' deleted at user workspace
```

### CODE REVIEW

**Comment by joaquimgamero** [comment]
✅ Tested on both personal workspace and organization workspace, apparently works fine!

Screenshot 2024-06-18 at 15 55 18

Screenshot 2024-06-18 at 15 49 36

**Review by joaquimgamero — APPROVED** [review]
(I approve only in the sense that I tested this and it works)

**Review by joshiesh — APPROVED** [review]
I ran a quick test on my end to add CodeCommit credentials into a workspace and seems to work just fine! I just can't verify the credentials are valid when adding a CodeCommit repo to the Launchpad.

```
./tw credentials add codecommit -n esha-test-codecommit -w scidev/testing --access-key $TEST_ACCESS_KEY --secret-key $TEST_SECRET_KEY

  New CODECOMMIT credentials 'esha-test-codecommit (6bJXQkPSFKQVjsuPW7jEDX)' added at [scidev / testing] workspace
  ```

**Comment by pgeadas** [comment]
Also tested it for workspace and all good.

**Comment by JaimeSeqLabs** [comment]
v0.9.3 [released](https://github.com/seqeralabs/tower-cli/releases/tag/v0.9.3) including AWS CodeCommit credentials support

**Pull request merged**
