### PR TITLE
Release CLI v0.6

### PR DESCRIPTION
**Pull request by jordeu**
## Description

This is the list of the issues to test. You can download the binaries from the artifacts section [here](https://github.com/seqeralabs/tower-cli/actions/runs/2188552505):

New features:
- [x] Support shared workspaces. Issue #76 and #105
- [x] Support Tower Agent. Issue #91
- [x] New environment variable `TOWER_OUTPUT_FORMAT`. Issue #183
- [x] Add container registry credentials. Issue #190
- [x] Add `--wait` option at compute-env creation and pipeline launch. #12
- [x] Custom run name #200 #150
- [x] Force delete a run #197

Improvements:
- [x] Clear error messages. Issue #194 #181 #182 #187
- [ ] Remove `--no-max` pagination option. #221
- [x] Allow to add a collaborator to a workspace #202
- [ ] Change HTTP Agent Header #192
- [ ] Updte dependencies and GraalVM #186
- [ ] Non-ASCII characters bug #161

### CODE REVIEW

**Comment by drpatelh** [comment]
I wonder if `TOWER_OUTPUT_FORMAT` is too vague and should be `TOWER_CLI_OUTPUT_FORMAT`. 

Following on from this I think this would be a good time to standardise all CLI specific environment variables to have the `TOWER_CLI_*` prefix?

**Comment by jordeu** [comment]
Ok, this is the first CLI specific environment variable. So for me make sense to always use `TOWER_CLI_...` prefix.

**Comment by pditommaso** [comment]
Then should not we use `TW_xxx` prefix?

**Comment by drpatelh** [comment]
Dunno about `TW_xxx`. Think `TOWER_CLI_xxx` is more explicit? May not be immediately obvious what the difference between `TW` and `TOWER_CLI` but as long as we are consistent I guess it doesn't matter.

**Comment by jordeu** [comment]
Given that the other Tower variables they start with `TOWER` I prefer `TOWER_CLI` because it is more explicit and if you list or grep them you get all of them together. I mean at the end `TOWER_ACCESS_TOKEN` and `TOWER_API_ENDPOINT` are also Tower CLI config variables. To add the `CLI` suffix is only to stress that they apply only at the CLI.

**Comment by pditommaso** [comment]
Fair enough

**Review by abhi18av — CHANGES_REQUESTED** [review]
I was able to confirm most of the updates however, in the comments below I highlight some areas which need to be tweaked.


#### The behavior of the CLI seems unstable wrt to the `container-reg` creds

- Addition of a `container-reg` credential - the cred gets created but an error is thrown on the CLI side ⚠️ 

```
+  >_ tw-dev credentials add container-reg -n temp-docker-io -u abhinav -p password -w 250554163114589
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.seqera.tower.cli.responses.CredentialsAdded and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:404)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1135)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1005)
	at io.seqera.tower.cli.utils.JsonHelper.prettyJson(JsonHelper.java:23)
	at io.seqera.tower.cli.utils.ResponseHelper.outputFormat(ResponseHelper.java:48)
	at io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:374)
	at io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:54)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.seqera.tower.cli.Tower.main(Tower.java:89)


```


- Deletion of a `container-reg` credential 🔴 
```
+  >_ tw-dev credentials delete -n "temp-docker-io"
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public io.seqera.tower.model.ContainerRegistryKeys()
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
	at java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:92)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:487)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:270)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1682)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:977)
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:838)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:363)
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:126)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:389)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:264)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:123)
	at io.seqera.tower.ApiClient.deserialize(ApiClient.java:647)
	at io.seqera.tower.ApiClient.invokeAPI(ApiClient.java:826)
	at io.seqera.tower.api.DefaultApi.listCredentialsWithHttpInfo(DefaultApi.java:5396)
	at io.seqera.tower.api.DefaultApi.listCredentials(DefaultApi.java:5347)
	at io.seqera.tower.cli.commands.credentials.AbstractCredentialsCmd.findCredentialsByName(AbstractCredentialsCmd.java:27)
	at io.seqera.tower.cli.commands.credentials.DeleteCmd.exec(DeleteCmd.java:43)
	at io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:373)
	at io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:54)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.seqera.tower.cli.Tower.main(Tower.java:89)



```


Testing the Agent (setup and crowds now).

**Comment by jordeu** [comment]
@abhi18av reported error has been fixed. You can download new artifacts from [here](https://github.com/seqeralabs/tower-cli/actions/runs/2188552505).

**Review by abhi18av — APPROVED** [review]
Looks good to merge - I was able to confirm the the testing criteria after the latest changes ✅

**Comment by jordeu** [comment]
Nice! Thanks @abhi18av !

**Pull request merged**
