### PR TITLE
Add overwrite option for tower entities

### LINKED ISSUE #338: Add --overwrite option for Tower entities
Add a new `--overwrite` option to recreate already existing Tower entities.

```[tasklist]
### Tasks
- [ ] #285
- [ ] Add --overwrite option for adding Organizations
- [ ] Add --overwrite option for adding Teams
- [ ] Add --overwrite option for adding Workspaces
- [ ] Add --overwrite option for adding Participants
- [ ] Add --overwrite option for adding Credentials
- [ ] Add --overwrite option for adding Secrets
- [ ] Add --overwrite option for adding Actions
- [ ] Add --overwrite option for adding Datasets
```

### PR DESCRIPTION
**Pull request by JaimeSeqLabs**
## Description

Add `--overwrite` option when creating:
+ Organizations
+ Teams
+ Workspaces
+ Participants
+ Credentials
+ Secrets
+ Actions
+ Datasets

Closes #338 

## Guidelines for testing
For each of the entity types in the description:

When trying to `add` (create) a new entity using a name/identifier that already exists in the context (workspace/personal wsp/organization)

Then the `add` command should fail ("Entity already exists")

When trying again adding the `--overwrite` option

Then the `add` command should create the new entity deleting the previous one with the same name

i.e.
```
# Given that an Organization named JaimeOrg already exists

# This should fail
$> tw organizations add -n JaimeOrg -f jaime-org

# This should work
$> tw organizations add --overwrite -n JaimeOrg -f jaime-new-org -d this is my new org
```

### CODE REVIEW

**Review by jordeu — APPROVED** [review]

**Comment by cbr7** [comment]
Finished checking all the options, all work fine with the exception of the credentials option. I was not able to overwrite an existing credential.

image

**Review by swampie — APPROVED** [review]

**Comment by jordeu** [comment]
I'm getting a reflection exception when trying to overwrite credentials (I get same exception only calling a `tw credentials list`):

```./tw credentials add agent -n overwrite --overwrite --connection-id=vallibierna
Exception in thread "main" org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively invoke method public void io.seqera.tower.model.AgentSecurityKeys.setShared(java.lang.Boolean) without it being registered for runtime reflection. Add it to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.MissingReflectionRegistrationUtils.forQueriedOnlyExecutable(MissingReflectionRegistrationUtils.java:97)
	at java.base@17.0.8/java.lang.reflect.Method.acquireMethodAccessor(Method.java:77)
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:566)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1682)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:977)
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:838)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:363)
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:126)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:389)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:264)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:123)
	at io.seqera.tower.ApiClient.deserialize(ApiClient.java:647)
	at io.seqera.tower.ApiClient.invokeAPI(ApiClient.java:826)
	at io.seqera.tower.api.DefaultApi.listCredentialsWithHttpInfo(DefaultApi.java:6341)
	at io.seqera.tower.api.DefaultApi.listCredentials(DefaultApi.java:6292)
	at io.seqera.tower.cli.commands.credentials.AbstractCredentialsCmd.findCredentialsByName(AbstractCredentialsCmd.java:27)
	at io.seqera.tower.cli.commands.credentials.AbstractCredentialsCmd.deleteCredentialsByName(AbstractCredentialsCmd.java:58)
	at io.seqera.tower.cli.commands.credentials.add.AbstractAddCmd.tryDeleteCredentials(AbstractAddCmd.java:65)
	at io.seqera.tower.cli.commands.credentials.add.AbstractAddCmd.exec(AbstractAddCmd.java:54)
	at io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:407)
	at io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:59)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.seqera.tower.cli.Tower.main(Tower.java:93)
```

**Comment by jordeu** [comment]
Fixed. Now to overwrite credentials it's working fine for me on linux.

**Comment by JaimeSeqLabs** [comment]
> Fixed. Now to overwrite credentials it's working fine for me on linux.

@cbr7 can you please try credentials override with this fix from @jordeu ?
I think this was the issue in MacOS

**Comment by cbr7** [comment]
@JaimeSeqLabs still not working for me, same issue as before:

image

**Pull request merged**
