### PR TITLE
Release v0.10.2

### PR DESCRIPTION
**Pull request by robnewman**
Bump version based on bugfix:

- Retrieving run stats is not working for failed workflows

### CODE REVIEW

**Comment by pditommaso** [comment]
Worth to update the changelog file

**Comment by robnewman** [comment]
> Worth to update the changelog file

This gets done automatically with the GHA, right (including `[release]` in the squash and merge command)?

From the docs:

> Include the text `[release]` in the merge commit message to trigger the release artifacts creation (i.e. `Release version X.Y.Z [release]`)

**Comment by JaimeSeqLabs** [comment]
@robnewman the changelog is created automatically from the commit list, we just need to make sure that the auto-generated list contains this specific change.

**Comment by andrew-dawson-seqera** [comment]
Jumping in here. I will reach out to @JaimeSeqLabs on Slack to clarify what needs to be done exactly and report back.

**Review by mbosio85 — APPROVED** [review]

**Comment by pditommaso** [comment]
Indeed. I didn't realise that there's a a changelog file in the project. Enough updating the version and (squash) merge with the `[release] bump version xxx` comment

**Pull request merged**
