### PR TITLE
chore: changes default url to https://api.cloud.seqera.io

### LINKED ISSUE #451: New Platform endpoint should be used in place of `tower.nf`
The URL reported by CLI tool is still using old `tower.nf` endpoint. It should be update to `cloud.seqera.io` 

```
https://tower.nf/orgs/seqeralabs/workspaces/showcase/watch/5CK3vQm4ydHqFe
```

### PR DESCRIPTION
**Pull request by swampie**
This PR changes the default api endpoint from the legacy `api.tower.nf` to the new `api.cloud.seqera.io`

No regression on testing

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]

**Comment by robnewman** [comment]
@tcrespog Aren't there additional incorrect references to `tower.nf` in the file `service-info.json` such as the links to Docs, Community, Feedback, `landingUrl`, `termsOfUseUrl`, `contentUrl`, and  `analytics.url`?

**Comment by tcrespog** [comment]
> Aren't there additional incorrect references to `tower.nf` in the file `src/test/resources/runcmd/info/service-info.json`

That is a test file, but OK: I've just updated the remaining references.

**Review by tcrespog — APPROVED** [review]
Tested and works successfully.

**Comment by robnewman** [comment]
@tcrespog I think this can probably be rebased and merged, no?

**Comment by pditommaso** [comment]
Surprised this was not yet merged

**Pull request merged**
