### PR TITLE
Release job to publish tower-cli to homebrew

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will add the release job to publish tower-cli to homebrew
1. add jreleaser PAT to build.yml
2. add brew packager to jreleaser.yml

### CODE REVIEW

**Comment by munishchouhan** [comment]
@jordeu Please review, you can refer to the same working config in wave-cli

https://github.com/seqeralabs/wave-cli/blob/d72d2c580cc1ce25ab61d7ed5a1474d0f6c31467/jreleaser.yml#L110-L119

**Review by jordeu — APPROVED** [review]

**Comment by marcodelapierre** [comment]
@pditommaso  ready for you

**Comment by pditommaso** [comment]
I'm not the one reviewing this

**Comment by marcodelapierre** [comment]
@jordeu  ready for merge then, I reckon :-)

**Comment by marcodelapierre** [comment]
Thanks @jordeu !  @munishchouhan , the Brew formulas will be generated at the next release, right?

Jordi, would this be a good reason to actually release a new version, and promote that it is now available via Homebrew?

**Comment by jordeu** [comment]
> Jordi, would this be a good reason to actually release a new version, and promote that it is now available via Homebrew?

I am not in charge of this project

**Comment by marcodelapierre** [comment]
oh thank you Jordi!   @JaimeSeqLabs   for you then 💥🚀

> would this be a good reason to actually release a new version, and promote that it is now available via Homebrew?

**Pull request merged**
